"""init

Revision ID: d39480655900
Revises:
Create Date: 2026-05-14 20:32:12.119184

"""

import sqlalchemy as sa
from alembic import op

revision = "d39480655900"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
