name: 'Terraform Plan & Notify'
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  TF_VERSION: "1.9.5"
  AWS_REGION: "eu-north-1"
defaults:
  run:
    shell: bash
    working-directory: ./infra
jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format Check
        run: terraform fmt -check
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Terraform Plan
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_github_pat_secret_arn: ${{ secrets.GITHUB_PAT_SECRET_ARN }}
          TF_VAR_telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TF_VAR_telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: terraform plan -no-color -input=false -out=tfplan
      - name: Upload Plan to S3
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp tfplan s3://tfplans-platform-prod-103242399399/plans/${{ github.run_id }}/tfplan
          echo "Plan uploaded: s3://tfplans-platform-prod-103242399399/plans/${{ github.run_id }}/tfplan"
      - name: Notify Telegram with Buttons
        if: github.ref == 'refs/heads/main'
        run: |
          RUN_ID="${{ github.run_id }}"
          
          KEYBOARD=$(jq -n \
            --arg id "$RUN_ID" \
            '{
              inline_keyboard: [
                [
                  {text: "✅ Apply", callback_data: ($id + "|apply")},
                  {text: "💥 Destroy", callback_data: ($id + "|destroy")},
                  {text: "❌ Cancel", callback_data: ($id + "|cancel")}
                ]
              ]
            }' | jq -c .)
          
          MSG="📋 *Terraform Plan Ready*
          
          🔹 Run ID: \`$RUN_ID\`
          🔹 Branch: \`${{ github.ref_name }}\`
          🔹 Commit: \`${{ github.sha }}\`
          
          Выбери действие:"
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "parse_mode=Markdown" \
            -d "text=$MSG" \
            -d "reply_markup=$KEYBOARD"
